// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CodersCupAward.Models;

public partial class ApplicationUser
{
    public int ApplicationUserId { get; set; }

    public int OrganizationId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string CellPhoneNumber { get; set; }

    public bool CanRecieveSMS { get; set; }

    public string EmailAddress { get; set; }

    public bool? EmailAddressVerified { get; set; }

    public DateTime? EmailVerificationSentDate { get; set; }

    public bool InvitePending { get; set; }

    public DateTime? InviteSentDate { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsPendingApproval { get; set; }

    public Guid ApplicationUserUniqueId { get; set; }

    public virtual ICollection<ApplicationUserActivityLog> ApplicationUserActivityLog { get; set; } = new List<ApplicationUserActivityLog>();

    public virtual ICollection<ApplicationUserPhoto> ApplicationUserPhoto { get; set; } = new List<ApplicationUserPhoto>();

    public virtual ICollection<ApplicationUserRole> ApplicationUserRole { get; set; } = new List<ApplicationUserRole>();

    public virtual ICollection<CoderPointTracking> CoderPointTracking { get; set; } = new List<CoderPointTracking>();

    public virtual Organization Organization { get; set; }
}