// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CodersCupAward.Models;

public partial class ApplicationUserActivityLog
{
    public int ApplicationUserActivityLogId { get; set; }

    public int ApplicationUserId { get; set; }

    public DateTime ActivityDate { get; set; }

    public string Activity { get; set; }

    public virtual ApplicationUser ApplicationUser { get; set; }
}