// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CodersCupAward.Models;

public partial class ApplicationSession
{
    public Guid ApplicationSessionId { get; set; }

    public string SessionData { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }
}