// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CodersCupAward.Models;

public partial class CoderPointTracking
{
    public int CoderPointTrackingId { get; set; }

    public int ApplicationUserId { get; set; }

    public int IterationId { get; set; }

    public string EntryReference { get; set; }

    public int? CoderPointMetricId { get; set; }

    public int Points { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ApplicationUser ApplicationUser { get; set; }
}