// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CodersCupAward.Models;

public partial class EmailLog
{
    public int EmailLogId { get; set; }

    public string EmailFromAddress { get; set; }

    public string EmailTo { get; set; }

    public string EmailCc { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public string ReplyTo { get; set; }

    public string AttachmentPath { get; set; }

    public string AttachmentName { get; set; }

    public DateTime InsertDate { get; set; }
}