// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CodersCupAward.Models;

public partial class Organization
{
    public int OrganizationId { get; set; }

    public string OrganizationName { get; set; }

    public string DepartmentTeamName { get; set; }

    public string Address { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsSetupComplete { get; set; }

    public virtual ICollection<ApplicationUser> ApplicationUser { get; set; } = new List<ApplicationUser>();

    public virtual ICollection<CoderPointMetric> CoderPointMetric { get; set; } = new List<CoderPointMetric>();

    public virtual ICollection<Iteration> Iteration { get; set; } = new List<Iteration>();
}